package com.satspulse.game

fun LocalizedText.resolve(language: AppLanguage): String = when (language) {
    AppLanguage.ES -> es
    AppLanguage.EN -> en
    AppLanguage.PT -> pt
}

fun languageLabel(language: AppLanguage): String = when (language) {
    AppLanguage.ES -> "ES"
    AppLanguage.EN -> "EN"
    AppLanguage.PT -> "PT"
}

fun tr(language: AppLanguage, key: String): String {
    val es = mapOf(
        "tagline" to "Golpeá el núcleo. Encadená combos. Entrá en fiebre.",
        "developer" to "ILLU ENTERTAINMENT",
        "play" to "JUGAR",
        "shop" to "SKIN LAB",
        "challenges" to "DESAFÍOS",
        "rank" to "RANGO",
        "best" to "RÉCORD",
        "goal" to "META",
        "locked" to "BLOQUEADO",
        "owned" to "TUYO",
        "use" to "USAR",
        "active" to "ACTIVA",
        "back" to "VOLVER",
        "paymentTitle" to "Desbloqueo Lightning",
        "paymentBody" to "El pago se procesa fuera del APK y el contenido se habilita cuando el servidor confirma el cobro.",
        "creating" to "Creando pago…",
        "checking" to "Verificando pago…",
        "verify" to "VERIFICAR",
        "openPayment" to "ABRIR PAGO",
        "close" to "CERRAR",
        "paid" to "¡Pago confirmado! Contenido desbloqueado.",
        "stillActive" to "Todavía no figura como pagado.",
        "verificationUnavailable" to "El proveedor no ofrece verificación automática para este cobro.",
        "tapCore" to "TOCÁ EL NÚCLEO",
        "combo" to "combo",
        "fever" to "FIEBRE",
        "perfect" to "PERFECTO",
        "great" to "GENIAL",
        "good" to "BIEN",
        "miss" to "FALLO",
        "resultsWin" to "PULSO DOMINADO",
        "resultsLose" to "CASI",
        "retry" to "REINTENTAR",
        "exit" to "SALIR",
        "misses" to "Fallos",
        "xp" to "XP",
        "claim" to "COBRAR XP",
        "claimed" to "COMPLETO",
        "progress" to "Progreso",
        "challengeIntro" to "Completá objetivos y subí de rango sin gastar sats.",
        "skinIntro" to "Cambiá el pulso visual de todo el juego.",
        "language" to "IDIOMA",
        "autoVerify" to "La app verifica el pago automáticamente durante unos instantes.",
        "stars" to "ESTRELLAS"
    )
    val en = mapOf(
        "tagline" to "Hit the core. Chain combos. Enter fever mode.",
        "developer" to "ILLU ENTERTAINMENT",
        "play" to "PLAY",
        "shop" to "SKIN LAB",
        "challenges" to "CHALLENGES",
        "rank" to "RANK",
        "best" to "BEST",
        "goal" to "GOAL",
        "locked" to "LOCKED",
        "owned" to "OWNED",
        "use" to "USE",
        "active" to "ACTIVE",
        "back" to "BACK",
        "paymentTitle" to "Lightning unlock",
        "paymentBody" to "Payment happens outside the APK. Content unlocks only after the server confirms payment.",
        "creating" to "Creating payment…",
        "checking" to "Checking payment…",
        "verify" to "VERIFY",
        "openPayment" to "OPEN PAYMENT",
        "close" to "CLOSE",
        "paid" to "Payment confirmed! Content unlocked.",
        "stillActive" to "Payment is still pending.",
        "verificationUnavailable" to "This provider does not expose automatic verification for this payment.",
        "tapCore" to "TAP THE CORE",
        "combo" to "combo",
        "fever" to "FEVER",
        "perfect" to "PERFECT",
        "great" to "GREAT",
        "good" to "GOOD",
        "miss" to "MISS",
        "resultsWin" to "PULSE MASTERED",
        "resultsLose" to "SO CLOSE",
        "retry" to "RETRY",
        "exit" to "EXIT",
        "misses" to "Misses",
        "xp" to "XP",
        "claim" to "CLAIM XP",
        "claimed" to "DONE",
        "progress" to "Progress",
        "challengeIntro" to "Complete objectives and rank up without spending sats.",
        "skinIntro" to "Change the visual pulse of the entire game.",
        "language" to "LANGUAGE",
        "autoVerify" to "The app automatically checks payment for a short time.",
        "stars" to "STARS"
    )
    val pt = mapOf(
        "tagline" to "Acerte o núcleo. Faça combos. Entre em febre.",
        "developer" to "ILLU ENTERTAINMENT",
        "play" to "JOGAR",
        "shop" to "SKIN LAB",
        "challenges" to "DESAFIOS",
        "rank" to "RANK",
        "best" to "RECORDE",
        "goal" to "META",
        "locked" to "BLOQUEADO",
        "owned" to "SEU",
        "use" to "USAR",
        "active" to "ATIVA",
        "back" to "VOLTAR",
        "paymentTitle" to "Desbloqueio Lightning",
        "paymentBody" to "O pagamento acontece fora do APK e o conteúdo libera quando o servidor confirma o pagamento.",
        "creating" to "Criando pagamento…",
        "checking" to "Verificando pagamento…",
        "verify" to "VERIFICAR",
        "openPayment" to "ABRIR PAGAMENTO",
        "close" to "FECHAR",
        "paid" to "Pagamento confirmado! Conteúdo desbloqueado.",
        "stillActive" to "O pagamento ainda está pendente.",
        "verificationUnavailable" to "O provedor não oferece verificação automática para este pagamento.",
        "tapCore" to "TOQUE NO NÚCLEO",
        "combo" to "combo",
        "fever" to "FEBRE",
        "perfect" to "PERFEITO",
        "great" to "ÓTIMO",
        "good" to "BOM",
        "miss" to "ERRO",
        "resultsWin" to "PULSO DOMINADO",
        "resultsLose" to "QUASE",
        "retry" to "TENTAR DE NOVO",
        "exit" to "SAIR",
        "misses" to "Erros",
        "xp" to "XP",
        "claim" to "PEGAR XP",
        "claimed" to "CONCLUÍDO",
        "progress" to "Progresso",
        "challengeIntro" to "Complete objetivos e suba de rank sem gastar sats.",
        "skinIntro" to "Mude o pulso visual de todo o jogo.",
        "language" to "IDIOMA",
        "autoVerify" to "O app verifica o pagamento automaticamente por alguns instantes.",
        "stars" to "ESTRELAS"
    )
    return when (language) {
        AppLanguage.ES -> es[key]
        AppLanguage.EN -> en[key]
        AppLanguage.PT -> pt[key]
    } ?: key
}
